name: scraper-pdx-jail

# Controls when the workflow will run
on:
  # Triggers the workflow to run every 4 hours
  schedule:
    - cron: '0 */4 * * *' 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo content
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@4.1.0
        with:
          python-version: '3.9.12'
          
      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute site scraper
        run:
          python scraper.py
          
      - name: commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions.users@noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push -f origin main
