name: scrape-inmates

on:
  schedule:
    - cron: '30 */3 * * *'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Scrape-PDX-Inmates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.12'

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute inmates spider
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        run:
          cd inmates_spider/inmates_spider/spiders && scrapy crawl inmates --nolog --overwrite-output="../../../csvs/inmate_details.csv"

      - name: Commit and push if changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions.users@noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest inmate data update: ${timestamp}" || exit 0
          git push -f origin main
  Update-Inmates-DB:
      - name: Update MongoDB inmates collection with new data
      - needs: Scrape-PDX-Inmates
        env:
          MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
        run:
          cd utils && python update_db.py --nolog
      
